language: go

go:
  - 1.10.x

before_install:
  - go get -v github.com/caoxiaolin/leetcode

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
